17-02

In [ ]:
pip install transformers

In [ ]:
import pandas as pd
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
result = tokenizer.tokenize('Here is the sentence I want embedding for.')
print(result)

['here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', 'for', '.']


In [ ]:
print(tokenizer.vocab['here'])

2182


In [ ]:
print(tokenizer.vocab['embedding'])

KeyError: 'embedding'

In [ ]:
print(tokenizer.vocab['em'])

7861


In [ ]:
print(tokenizer.vocab['##bed'])

8270


In [ ]:
print(tokenizer.vocab['##ding'])

4667


In [ ]:
print(tokenizer.vocab['##s'])

2015


In [ ]:
with open('vocabulary.txt', 'w') as f:
  for token in tokenizer.vocab.keys():
    f.write(token + '\n')

In [ ]:
df = pd.read_fwf('vocabulary.txt', header=None)
df

0
0          [PAD]
1      [unused0]
2      [unused1]
3      [unused2]
4      [unused3]
...          ...
30517        ##．
30518        ##／
30519        ##：
30520        ##？
30521        ##～

[30522 rows x 1 columns]

In [ ]:
print('단어 집합의 크기 :', len(df))

단어 집합의 크기 : 30522


In [ ]:
df.loc[4667].values[0]

'##ding'

In [ ]:
df.loc[102].values[0]

'[SEP]'

17-03

In [ ]:
pip install transformers

In [ ]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [ ]:
model = TFBertForMaskedLM.from_pretrained('bert-base-uncased')
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
#문장: "Soccer is a really fun [MASK]."
#토큰화: ['Soccer', 'is', 'a', 'really', 'fun', '[MASK]', '.']
#정수 인코딩: 각 토큰에 고유한 정수를 할당
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [ ]:
#정수 인코딩 결과
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [ ]:
#문장을 구분하는 세그먼트 인코딩 결과
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [ ]:
#어텐션 마스크
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [ ]:
#마스크드 언어 모델([MASK] 토큰) 예측
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

Device set to use 0


In [ ]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.7672247886657715,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.16400092840194702,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.015704672783613205,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.007100082468241453,
  'token': 2154,
  'token_str': 'day',
  'sequence': 'soccer is a really fun day.'},
 {'score': 0.00612697284668684,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'}]

In [ ]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.3112408220767975,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'the avengers is a really fun game.'},
 {'score': 0.12129494547843933,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.09142865985631943,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.03700055927038193,
  'token': 6172,
  'token_str': 'adventure',
  'sequence': 'the avengers is a really fun adventure.'},
 {'score': 0.03315597027540207,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'}]

In [ ]:
pip('I went to [MASK] this morning.')

[{'score': 0.30449146032333374,
  'token': 2147,
  'token_str': 'work',
  'sequence': 'i went to work this morning.'},
 {'score': 0.25700804591178894,
  'token': 2793,
  'token_str': 'bed',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.08158306032419205,
  'token': 2082,
  'token_str': 'school',
  'sequence': 'i went to school this morning.'},
 {'score': 0.07317690551280975,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.062069736421108246,
  'token': 2465,
  'token_str': 'class',
  'sequence': 'i went to class this morning.'}]

17-04 한국어 BERT의 마스크드 언어 모델

In [ ]:
pip install transformers

SyntaxError: invalid syntax (<ipython-input-19-5161828de823>, line 1)

In [ ]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [ ]:
model = TFBertForMaskedLM.from_pretrained('skt/kobert-base', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained('skt/kobert-base')

OSError: skt/kobert-base is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [ ]:
inputs = tokenizer('축구는 정말 재미있는 [MASK]다.', return_tensors='tf')
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 21), dtype=int32, numpy=
array([[  101,  1465, 30014, 30020, 29991, 30014, 29992, 30017, 30021,
         1464, 30008, 30025, 29995, 30006, 30022,   100,   103,  1457,
        30006,  1012,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 21), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 21), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>}


In [ ]:
#정수 인코딩 결과
print(inputs['input_ids'])

tf.Tensor(
[[  101  1465 30014 30020 29991 30014 29992 30017 30021  1464 30008 30025
  29995 30006 30022   100   103  1457 30006  1012   102]], shape=(1, 21), dtype=int32)


In [ ]:
#세그먼트 인코딩 결과
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]], shape=(1, 21), dtype=int32)


In [ ]:
#어텐션 마스크
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]], shape=(1, 21), dtype=int32)


In [ ]:
#마스크드 언어 모델([MASK] 토큰) 예측 결과

In [ ]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

Device set to use 0


In [ ]:
pip('축구는 정말 재미있는 [MASK]다.')

[{'score': 0.5771374702453613,
  'token': 100,
  'token_str': '[UNK]',
  'sequence': '축구는 정말 다.'},
 {'score': 0.090544193983078,
  'token': 1011,
  'token_str': '-',
  'sequence': '축구는 정말 - 다.'},
 {'score': 0.08730615675449371,
  'token': 1012,
  'token_str': '.',
  'sequence': '축구는 정말. 다.'},
 {'score': 0.06070976331830025,
  'token': 1010,
  'token_str': ',',
  'sequence': '축구는 정말, 다.'},
 {'score': 0.02167106419801712,
  'token': 1024,
  'token_str': ':',
  'sequence': '축구는 정말 : 다.'}]

In [ ]:
pip('어벤져스는 정말 재미있는 [MASK]다.')

[{'score': 0.5553070306777954,
  'token': 100,
  'token_str': '[UNK]',
  'sequence': '어벤져스는 정말 다.'},
 {'score': 0.09212030470371246,
  'token': 1011,
  'token_str': '-',
  'sequence': '어벤져스는 정말 - 다.'},
 {'score': 0.09119044989347458,
  'token': 1012,
  'token_str': '.',
  'sequence': '어벤져스는 정말. 다.'},
 {'score': 0.06420046091079712,
  'token': 1010,
  'token_str': ',',
  'sequence': '어벤져스는 정말, 다.'},
 {'score': 0.021786145865917206,
  'token': 2133,
  'token_str': '...',
  'sequence': '어벤져스는 정말... 다.'}]

In [ ]:
pip('나는 오늘 아침에 [MASK]에 출근을 했다.')

[{'score': 0.6939572691917419,
  'token': 100,
  'token_str': '[UNK]',
  'sequence': '나는 오늘 아침에 에 출근을.'},
 {'score': 0.09570560604333878,
  'token': 1010,
  'token_str': ',',
  'sequence': '나는 오늘 아침에, 에 출근을.'},
 {'score': 0.030898522585630417,
  'token': 30021,
  'token_str': '##ᆫ',
  'sequence': '나는 오늘 아침엔 에 출근을.'},
 {'score': 0.03017170913517475,
  'token': 1012,
  'token_str': '.',
  'sequence': '나는 오늘 아침에. 에 출근을.'},
 {'score': 0.022108497098088264,
  'token': 30022,
  'token_str': '##ᆯ',
  'sequence': '나는 오늘 아침엘 에 출근을.'}]